config/routes.rb
Cathub::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins

  root to: 'posts#index'

  resources :users, only:   [ :show ]
  resources :posts, except: [ :edit, :new ]
  resources :likes, only:   [ :create ] do
    collection { delete :destroy }
  end

  namespace :admin do
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_one :media, autosave: true, dependent: :destroy; accepts_nested_attributes_for :media
  has_many :likes

  validates :description, length: { maximum: 300 }, allow_nil: true

  scope :video, -> { joins(:media).where('media.video = ?', true) }
  scope :image, -> { joins(:media).where('media.video = ?', false) }
  scope :popularity, -> { order('posts.likes_count DESC') }

  # TOPS
  scope :daily,    -> type  { send(type).where('posts.created_at >= ?', 1.day.ago).limit(5).popularity }
  scope :weekly,   -> type  { send(type).where('posts.created_at >= ?', 7.day.ago).limit(5).popularity }
  scope :all_time, -> type  { send(type).limit(5).popularity }

  def liked!
    increment! :likes_count, 1
  end

  def unliked!
    increment! :likes_count, -1
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [ :update, :destroy, :create ]
  before_filter :find_post!, only: [ :show, :update, :destroy ]
  before_filter :prepare_section, only: [ :index ]
  before_filter :prepare_sort, only: [ :index ]

  def index
    @posts = @section.order(@sort).page(params[:page]).includes(:user).includes(:media)
    @post  = Post.new.tap { |post| post.build_media }

    prepare_top_cats unless request.xhr?

    respond_to do |format|
      format.html
      format.json do
        render json: { entries: render_to_string(partial: 'post', collection: @posts), last: @posts.last_page? }
      end
    end
  end

  def show
  end

  def create
    @post = Post.create(post_params)

    if @post.persisted?
      redirect_to root_path, notice: I18n.t('flash.posts.create.notice')
    else
      redirect_to root_path, alert: I18n.t('flash.posts.create.alert')
    end
  end

  def update
    @post.update post_params

    if @post.valid?
    else
    end
  end

  def destroy
    @post.destroy

    render nothing: true, status: 202
  end

  private

  def post_params
    params.require(:post).permit(:description, media_attributes: [ :image, :url ]).merge(user_id: current_user.id)
  end

  def find_post!
    @post = Post.find(params[:id])
  end

  def prepare_section
    @section = %w(video image).include?(params[:section]) ? Post.send(params[:section].to_sym) : Post.all
  end

  def prepare_sort
    @sort = %w(likes_count).include?(params[:sort]) ? "posts.#{params[:sort]} DESC, posts.created_at DESC" : 'posts.created_at DESC'
  end

  def prepare_top_cats
    @daily_top_videos    = Post.daily(:video)
    @daily_top_images    = Post.daily(:image)
    @weekly_top_videos   = Post.weekly(:video)
    @weekly_top_images   = Post.weekly(:image)
    @all_time_top_videos = Post.all_time(:video)
    @all_time_top_images = Post.all_time(:image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def current_section
    %w(video image).include?(params[:section]) ? params[:section].inquiry : 'all'.inquiry
  end

  def current_sort
    %w(likes_count).include?(params[:sort]) ? params[:sort].inquiry : 'date'.inquiry
  end

  def post_description(post)
    "#{ post.description.present?? truncate(post.description, length: 50) : t('.no_description') } #{ t '.by', name: truncate(post.user.name, length: 20) } : <span class='top-entry-likes'>#{post.likes_count} <i class='icon-heart'></i></span>".html_safe
  end
end

app/views/posts/_post.erb
<% cache post do %>

<div id='post-<%= post.id %>' class='post'>
  <%- if (user_signed_in? and current_user.owns?(post)) or admin_signed_in? %>
    <%= link_to t('common.x'), post, method: 'delete', remote: true, class: 'close destroy-post', data: { confirm: t('common.are_you_sure?') } %>
  <% end %>

  <div class='post-description'>
    <%= simple_format post.description %>
  </div>

  <% if post.media.video? %>
    <iframe width="560" height="315" src="<%= post.media.url %>?html5=1" frameborder="0" allowfullscreen></iframe>
  <% else %>
    <%- if post.media.gif? %>
      <div class='gif-image-container'>
        <%= image_tag post.media.image.url(:thumb), class: 'gif-image' %>
        <div class='gif-info-overlay'> <%= t '.gif' %> </div>

        <%= image_tag post.media.image.url(:large), class: 'hidden gif-animation' %>
      </div>
    <% else %>
      <div class='regular-image-container'>
        <%= image_tag post.media.image.url(:thumb), class: 'regular-image', data: { author: post.user.name, description: post.description } %>
        <%= image_tag post.media.image.url(:large), class: 'hidden image-large-version' %>
      </div>
    <% end %>
  <% end %>

  <div class='post-details'>
    <div class='post-author pull-left'>
      <%= link_to post.user.name, user_path(post.user) %>,
      <span class='time'> <%= distance_of_time_in_words_to_now post.created_at %> <%= t 'common.ago' %> </span>
    </div>

    <div class='like-bar pull-right'>
      <%= link_to likes_path(id: post.id), method: 'post', remote: true, class: "like #{ current_user.liked?(post) ? 'hidden' : '' }" do %>
        <%= icon_label 'icon-heart-empty like' %>
      <% end %>

      <%= link_to likes_path(id: post.id), method: 'delete', remote: true, class: "unlike #{ current_user.liked?(post) ? '' : 'hidden' }" do %>
        <%= icon_label 'icon-heart unlike' %>
      <% end %>

      <span class='current-likes-count'> <%= post.likes_count %> </span>
    </div>
  </div>
</div>

<hr />

<% end %>

app/views/posts/_tops.erb
<div id='cat-tops' class='well span4 pull-right'>
  <h3><%= t '.header' %> <%= icon_label 'icon-star' %></h3>
  <hr />

  <div id='daily-tops'>
    <h3><%= t '.daily' %></h4>
    <h5> <%= t '.video' %> </h5>
    <div class='cat-top-entries'>
      <% @daily_top_videos.each do |post| %>
        <%= link_to post_description(post), post %>
      <% end %>
    </div>
    <h5> <%= t '.image' %> </h5>
    <div class='cat-top-entries'>
      <% @daily_top_images.each do |post| %>
        <%= link_to post_description(post), post %>
      <% end %>
    </div>
  </div>

  <hr />

  <div id='weekle-tops'>
    <h3><%= t '.weekly' %></h4>
    <h5> <%= t '.video' %> </h5>
    <div class='cat-top-entries'>
      <% @weekly_top_videos.each do |post| %>
        <%= link_to post_description(post), post %>
      <% end %>
    </div>
    <h5> <%= t '.image' %> </h5>
    <div class='cat-top-entries'>
      <% @weekly_top_images.each do |post| %>
        <%= link_to post_description(post), post %>
      <% end %>
    </div>
  </div>

  <hr />

  <div id='all-time-tops'>
    <h3><%= t '.all_time' %></h4>
    <h5> <%= t '.video' %> </h5>
    <div class='cat-top-entries'>
      <% @all_time_top_videos.each do |post| %>
        <%= link_to post_description(post), post %>
      <% end %>
    </div>
    <h5> <%= t '.image' %> </h5>
    <div class='cat-top-entries'>
      <% @all_time_top_images.each do |post| %>
        <%= link_to post_description(post), post %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div id='posts-header'>
  <div id='posts-navigation'>
    <ul class='nav nav-pills'>
      <li class='<%= current_section.all?? "active" : "" %>'> <%= link_to t('.all'), posts_path %> </li>
      <li class='<%= current_section.video?? "active" : "" %>'> <%= link_to t('.video'), posts_path(section: 'video') %> </li>
      <li class='<%= current_section.image?? "active" : "" %>'> <%= link_to t('.image'), posts_path(section: 'image') %> </li>
    </ul>
  </div>

  <div id='posts-sorting'>
    <h3> <%= t '.sort_by' %> </h3>
    <ul class='nav nav-pills'>
      <%- unless current_section.all? %>
        <li class='<%= current_sort.date?? "active" : "" %>'> <%= link_to t('.date_sort'), posts_path(sort: 'date', section: current_section) %> </li>
        <li class='<%= current_sort.likes_count?? "active" : "" %>'> <%= link_to t('.likes_sort'), posts_path(sort: 'likes_count', section: current_section) %> </li>
      <% else %>
        <li class='<%= current_sort.date?? "active" : "" %>'> <%= link_to t('.date_sort'), posts_path(sort: 'date') %> </li>
        <li class='<%= current_sort.likes_count?? "active" : "" %>'> <%= link_to t('.likes_sort'), posts_path(sort: 'likes_count') %> </li>
      <% end %>
    </ul>
  </div>
</div>

<hr />

<%- if user_signed_in? %>
  <%- if current_section.all? %>
    <%= link_to t('.new'), nil, class: 'btn btn-danger', id: 'new-post-form-toggler' %>
  <% end %>

  <div id='new-post-form-container' class='well'>
    <%= simple_form_for @post, html: { multipart: true, id: 'new-post' } do |form| %>
      <div class='form-inputs'>
        <div id='media-switch'>
          <%= icon_label 'icon-picture active', nil, id: 'image-uploader' %>
          <%= icon_label 'icon-youtube', nil, id: 'video-uploader' %>
        </div>

        <%= form.simple_fields_for :media do |media| %>
          <div id='image-uploader-container'> <%= media.input :image, as: :file %> </div>
          <div id='video-uploader-container'> <%= media.input :url, placeholder: t('.video_placeholder'), input_html: { class: 'span5' } %> </div>
        <% end %>

        <%= form.input :description, input_html: { class: 'span5' } %>
      </div>

      <%= form.button :submit, t('common.submit'), data: { disable_with: t('common.please_wait') } %>
    <% end %>
  </div>
<% else %>
  <%- if current_section.all? %>
    <%= link_to t('.new'), new_user_session_path, class: 'btn btn-danger' %>
  <% end %>
<% end %>


<div class='row'>
  <div id='posts' class='span6 pull-left' data-page='1' data-last-page='<%= @posts.last_page? %>'>
    <%= render @posts %>
  </div>

  <% cache 'tops', skip_digest: true do %>
    <%= render 'tops' %>
  <% end %>
</div>

<%= render 'image_modal' %>

app/views/posts/show.html.erb
<% if @post.media.video? %>
  <iframe width="560" height="315" src="<%= @post.media.url %>?html5=1" frameborder="0" allowfullscreen></iframe>
<% else %>
  <%= image_tag @post.media.image.url(:large) %>
<% end %>