config/routes.rb
Cathub::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins

  root to: 'posts#index'

  resources :users, only:   [ :show ]
  resources :posts, except: [ :edit, :new ]
  resources :likes, only:   [ :create ] do
    collection { delete :destroy }
  end

  namespace :admin do
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cathub</title>
  <%= stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "admin", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body id='admin-<%= controller_name.dasherize %>' data-action='<%= action_name.dasherize %>'>

  <div id='wrapper'>
    <%= render 'admin/header'  %>
    <%= render 'notifications' %>

    <div class='container' id='content'>
      <%= yield %>

      <div id='loader' class='hidden'> <%= image_tag 'loader.gif' %> </div>
      <div id='backdrop' class='modal-backdrop hidden'> </div>

      <div id='push'></div>
    </div>
  </div>

  <%= render 'footer' %>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t 'title' %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body id='<%= controller_path.dasherize.gsub('/', '-') %>' data-action='<%= action_name.dasherize %>'>

<div class='page-container'>
  <div id='wrapper'>
    <%= render 'header'        %>
    <%= render 'notifications' %>

    <div class='container' id='content'>
      <%= yield %>

      <div id='loader' class='hidden'> <%= image_tag 'loader.gif' %> </div>
      <div id='backdrop' class='modal-backdrop hidden'> </div>

      <div id='push'></div>
    </div>
  </div>

  <%- unless Rails.env.development? %>
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?88"></script>
  <% end %>

  <%= render 'sign_in_modal' unless user_signed_in? %>
  <%= render 'footer' %>
</div>

</body>

</html>